// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_hprobit
Rcpp::List cpp_hprobit(const Rcpp::List& Xlist, const Rcpp::List& Ylist, const arma::colvec& mean_prior, const arma::mat& prec_prior, const arma::ivec& ncategories, const Rcpp::List& gammas_start, const arma::colvec& beta_start, const arma::vec& proposal_variance, const int iterations, const int burnin, const int thin, const int seed, const int verbose);
RcppExport SEXP _masteruppsatsr_cpp_hprobit(SEXP XlistSEXP, SEXP YlistSEXP, SEXP mean_priorSEXP, SEXP prec_priorSEXP, SEXP ncategoriesSEXP, SEXP gammas_startSEXP, SEXP beta_startSEXP, SEXP proposal_varianceSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Xlist(XlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Ylist(YlistSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mean_prior(mean_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prec_prior(prec_priorSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ncategories(ncategoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gammas_start(gammas_startSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type proposal_variance(proposal_varianceSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hprobit(Xlist, Ylist, mean_prior, prec_prior, ncategories, gammas_start, beta_start, proposal_variance, iterations, burnin, thin, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hprobit_tune
Rcpp::List cpp_hprobit_tune(const Rcpp::List& x_list, const Rcpp::List& y_list, const arma::colvec& mean_prior, const arma::mat& prec_prior, const arma::ivec& ncategories, const Rcpp::List& gamma_start, const arma::colvec& beta_start, const arma::vec& tune_start, double target_acceptance_rate, double target_epsilon, bool stop_early, int max_iterations, int window_size, const int seed, int verbose);
RcppExport SEXP _masteruppsatsr_cpp_hprobit_tune(SEXP x_listSEXP, SEXP y_listSEXP, SEXP mean_priorSEXP, SEXP prec_priorSEXP, SEXP ncategoriesSEXP, SEXP gamma_startSEXP, SEXP beta_startSEXP, SEXP tune_startSEXP, SEXP target_acceptance_rateSEXP, SEXP target_epsilonSEXP, SEXP stop_earlySEXP, SEXP max_iterationsSEXP, SEXP window_sizeSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_list(x_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mean_prior(mean_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prec_prior(prec_priorSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ncategories(ncategoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_start(gamma_startSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tune_start(tune_startSEXP);
    Rcpp::traits::input_parameter< double >::type target_acceptance_rate(target_acceptance_rateSEXP);
    Rcpp::traits::input_parameter< double >::type target_epsilon(target_epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type stop_early(stop_earlySEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hprobit_tune(x_list, y_list, mean_prior, prec_prior, ncategories, gamma_start, beta_start, tune_start, target_acceptance_rate, target_epsilon, stop_early, max_iterations, window_size, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hprobit_pt
Rcpp::List cpp_hprobit_pt(const Rcpp::List& xlist, const Rcpp::List& ylist, const arma::colvec& beta_mean_prior, const arma::mat& beta_prec_prior, const arma::ivec& ncategories, const Rcpp::List& gamma_start, const arma::colvec& beta_start, const Rcpp::List& proposal_variances, const arma::vec inv_temperature_ladder, const int iterations, const int burnin, const int thin, const int seed, const bool complete_swapping, const int verbose);
RcppExport SEXP _masteruppsatsr_cpp_hprobit_pt(SEXP xlistSEXP, SEXP ylistSEXP, SEXP beta_mean_priorSEXP, SEXP beta_prec_priorSEXP, SEXP ncategoriesSEXP, SEXP gamma_startSEXP, SEXP beta_startSEXP, SEXP proposal_variancesSEXP, SEXP inv_temperature_ladderSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP seedSEXP, SEXP complete_swappingSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ylist(ylistSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta_mean_prior(beta_mean_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_prec_prior(beta_prec_priorSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ncategories(ncategoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_start(gamma_startSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type proposal_variances(proposal_variancesSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type inv_temperature_ladder(inv_temperature_ladderSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_swapping(complete_swappingSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hprobit_pt(xlist, ylist, beta_mean_prior, beta_prec_prior, ncategories, gamma_start, beta_start, proposal_variances, inv_temperature_ladder, iterations, burnin, thin, seed, complete_swapping, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hprobit_tune_pt
Rcpp::List cpp_hprobit_tune_pt(const Rcpp::List& x_list, const Rcpp::List& y_list, const arma::colvec& mean_prior, const arma::mat& prec_prior, const arma::ivec& ncategories, const Rcpp::List& gamma_start, const arma::colvec& beta_start, const Rcpp::List& proposal_variance, const bool tune_proposal_variance, const double target_acceptance_rate, const double target_acceptance_epsilon, const int proposal_window_size, const arma::vec inv_temperature_ladder_start, const bool tune_ladder, const double target_temp_swap_accept_rate, const double target_temp_swap_accept_epsilon, const int temp_window_size, const double temp_window_size_growth_factor, const double temp_ladder_learning_rate, const int iterations, const bool stop_early, const int seed, const bool complete_swapping, const int verbose);
RcppExport SEXP _masteruppsatsr_cpp_hprobit_tune_pt(SEXP x_listSEXP, SEXP y_listSEXP, SEXP mean_priorSEXP, SEXP prec_priorSEXP, SEXP ncategoriesSEXP, SEXP gamma_startSEXP, SEXP beta_startSEXP, SEXP proposal_varianceSEXP, SEXP tune_proposal_varianceSEXP, SEXP target_acceptance_rateSEXP, SEXP target_acceptance_epsilonSEXP, SEXP proposal_window_sizeSEXP, SEXP inv_temperature_ladder_startSEXP, SEXP tune_ladderSEXP, SEXP target_temp_swap_accept_rateSEXP, SEXP target_temp_swap_accept_epsilonSEXP, SEXP temp_window_sizeSEXP, SEXP temp_window_size_growth_factorSEXP, SEXP temp_ladder_learning_rateSEXP, SEXP iterationsSEXP, SEXP stop_earlySEXP, SEXP seedSEXP, SEXP complete_swappingSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_list(x_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mean_prior(mean_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prec_prior(prec_priorSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ncategories(ncategoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_start(gamma_startSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type proposal_variance(proposal_varianceSEXP);
    Rcpp::traits::input_parameter< const bool >::type tune_proposal_variance(tune_proposal_varianceSEXP);
    Rcpp::traits::input_parameter< const double >::type target_acceptance_rate(target_acceptance_rateSEXP);
    Rcpp::traits::input_parameter< const double >::type target_acceptance_epsilon(target_acceptance_epsilonSEXP);
    Rcpp::traits::input_parameter< const int >::type proposal_window_size(proposal_window_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type inv_temperature_ladder_start(inv_temperature_ladder_startSEXP);
    Rcpp::traits::input_parameter< const bool >::type tune_ladder(tune_ladderSEXP);
    Rcpp::traits::input_parameter< const double >::type target_temp_swap_accept_rate(target_temp_swap_accept_rateSEXP);
    Rcpp::traits::input_parameter< const double >::type target_temp_swap_accept_epsilon(target_temp_swap_accept_epsilonSEXP);
    Rcpp::traits::input_parameter< const int >::type temp_window_size(temp_window_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type temp_window_size_growth_factor(temp_window_size_growth_factorSEXP);
    Rcpp::traits::input_parameter< const double >::type temp_ladder_learning_rate(temp_ladder_learning_rateSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const bool >::type stop_early(stop_earlySEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_swapping(complete_swappingSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hprobit_tune_pt(x_list, y_list, mean_prior, prec_prior, ncategories, gamma_start, beta_start, proposal_variance, tune_proposal_variance, target_acceptance_rate, target_acceptance_epsilon, proposal_window_size, inv_temperature_ladder_start, tune_ladder, target_temp_swap_accept_rate, target_temp_swap_accept_epsilon, temp_window_size, temp_window_size_growth_factor, temp_ladder_learning_rate, iterations, stop_early, seed, complete_swapping, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fmeasure_distribution
arma::vec cpp_fmeasure_distribution(arma::mat predictions, arma::vec reference, int n_labels);
RcppExport SEXP _masteruppsatsr_cpp_fmeasure_distribution(SEXP predictionsSEXP, SEXP referenceSEXP, SEXP n_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type n_labels(n_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fmeasure_distribution(predictions, reference, n_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_classification_metric_distributions
Rcpp::List cpp_classification_metric_distributions(arma::mat predictions, arma::vec reference, int n_labels);
RcppExport SEXP _masteruppsatsr_cpp_classification_metric_distributions(SEXP predictionsSEXP, SEXP referenceSEXP, SEXP n_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type n_labels(n_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_classification_metric_distributions(predictions, reference, n_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_harmonic_rowmeans
arma::vec cpp_harmonic_rowmeans(arma::mat variables);
RcppExport SEXP _masteruppsatsr_cpp_harmonic_rowmeans(SEXP variablesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type variables(variablesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_harmonic_rowmeans(variables));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compare_distributions
Rcpp::List cpp_compare_distributions(arma::vec dist1, arma::vec dist2);
RcppExport SEXP _masteruppsatsr_cpp_compare_distributions(SEXP dist1SEXP, SEXP dist2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type dist1(dist1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dist2(dist2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compare_distributions(dist1, dist2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_diff_distributions
arma::vec cpp_diff_distributions(arma::vec dist1, arma::vec dist2);
RcppExport SEXP _masteruppsatsr_cpp_diff_distributions(SEXP dist1SEXP, SEXP dist2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type dist1(dist1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dist2(dist2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_diff_distributions(dist1, dist2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rmse_dist
arma::vec cpp_rmse_dist(arma::mat predictions, arma::mat reference, int ndraws);
RcppExport SEXP _masteruppsatsr_cpp_rmse_dist(SEXP predictionsSEXP, SEXP referenceSEXP, SEXP ndrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rmse_dist(predictions, reference, ndraws));
    return rcpp_result_gen;
END_RCPP
}
// cpp_moving_window_rhat
arma::vec cpp_moving_window_rhat(const arma::mat& chains, int for_every, int window_size);
RcppExport SEXP _masteruppsatsr_cpp_moving_window_rhat(SEXP chainsSEXP, SEXP for_everySEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type chains(chainsSEXP);
    Rcpp::traits::input_parameter< int >::type for_every(for_everySEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_moving_window_rhat(chains, for_every, window_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cumulative_rhat
arma::vec cpp_cumulative_rhat(const arma::mat& chains, int for_every);
RcppExport SEXP _masteruppsatsr_cpp_cumulative_rhat(SEXP chainsSEXP, SEXP for_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type chains(chainsSEXP);
    Rcpp::traits::input_parameter< int >::type for_every(for_everySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cumulative_rhat(chains, for_every));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_masteruppsatsr_cpp_hprobit", (DL_FUNC) &_masteruppsatsr_cpp_hprobit, 13},
    {"_masteruppsatsr_cpp_hprobit_tune", (DL_FUNC) &_masteruppsatsr_cpp_hprobit_tune, 15},
    {"_masteruppsatsr_cpp_hprobit_pt", (DL_FUNC) &_masteruppsatsr_cpp_hprobit_pt, 15},
    {"_masteruppsatsr_cpp_hprobit_tune_pt", (DL_FUNC) &_masteruppsatsr_cpp_hprobit_tune_pt, 24},
    {"_masteruppsatsr_cpp_fmeasure_distribution", (DL_FUNC) &_masteruppsatsr_cpp_fmeasure_distribution, 3},
    {"_masteruppsatsr_cpp_classification_metric_distributions", (DL_FUNC) &_masteruppsatsr_cpp_classification_metric_distributions, 3},
    {"_masteruppsatsr_cpp_harmonic_rowmeans", (DL_FUNC) &_masteruppsatsr_cpp_harmonic_rowmeans, 1},
    {"_masteruppsatsr_cpp_compare_distributions", (DL_FUNC) &_masteruppsatsr_cpp_compare_distributions, 2},
    {"_masteruppsatsr_cpp_diff_distributions", (DL_FUNC) &_masteruppsatsr_cpp_diff_distributions, 2},
    {"_masteruppsatsr_cpp_rmse_dist", (DL_FUNC) &_masteruppsatsr_cpp_rmse_dist, 3},
    {"_masteruppsatsr_cpp_moving_window_rhat", (DL_FUNC) &_masteruppsatsr_cpp_moving_window_rhat, 3},
    {"_masteruppsatsr_cpp_cumulative_rhat", (DL_FUNC) &_masteruppsatsr_cpp_cumulative_rhat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_masteruppsatsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
