// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_hprobit
Rcpp::List cpp_hprobit(const Rcpp::List Xlist, const Rcpp::List Ylist, const arma::colvec meanPrior, const arma::mat precPrior, const int fixZero, const arma::ivec ncat, const Rcpp::List gammaStart, const arma::colvec betaStart, const arma::vec tune, const int iterations, const int burnin, const int thin, const int seed, const int verbose);
RcppExport SEXP _masteruppsatsr_cpp_hprobit(SEXP XlistSEXP, SEXP YlistSEXP, SEXP meanPriorSEXP, SEXP precPriorSEXP, SEXP fixZeroSEXP, SEXP ncatSEXP, SEXP gammaStartSEXP, SEXP betaStartSEXP, SEXP tuneSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type Xlist(XlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Ylist(YlistSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type meanPrior(meanPriorSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type precPrior(precPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type fixZero(fixZeroSEXP);
    Rcpp::traits::input_parameter< const arma::ivec >::type ncat(ncatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gammaStart(gammaStartSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type betaStart(betaStartSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type tune(tuneSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hprobit(Xlist, Ylist, meanPrior, precPrior, fixZero, ncat, gammaStart, betaStart, tune, iterations, burnin, thin, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hprobit_pt
Rcpp::List cpp_hprobit_pt(const Rcpp::List& xlist, const Rcpp::List& ylist, const arma::colvec& mean_prior, const arma::mat& prec_prior, const int fix_zero, const arma::ivec& ncategories, const Rcpp::List& gamma_start, const arma::colvec& beta_start, const Rcpp::List& tune, const int ntemperatures, const arma::ivec temperature_ladder, const double target_temp_swap_accept_ratio, const int temp_window_size, const double temp_window_size_growth_factor, const double temp_ladder_learning_rate, const int iterations, const int burnin, const int thin, const int seed, bool complete_swapping, const int verbose);
RcppExport SEXP _masteruppsatsr_cpp_hprobit_pt(SEXP xlistSEXP, SEXP ylistSEXP, SEXP mean_priorSEXP, SEXP prec_priorSEXP, SEXP fix_zeroSEXP, SEXP ncategoriesSEXP, SEXP gamma_startSEXP, SEXP beta_startSEXP, SEXP tuneSEXP, SEXP ntemperaturesSEXP, SEXP temperature_ladderSEXP, SEXP target_temp_swap_accept_ratioSEXP, SEXP temp_window_sizeSEXP, SEXP temp_window_size_growth_factorSEXP, SEXP temp_ladder_learning_rateSEXP, SEXP iterationsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP seedSEXP, SEXP complete_swappingSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ylist(ylistSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mean_prior(mean_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prec_prior(prec_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type fix_zero(fix_zeroSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ncategories(ncategoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_start(gamma_startSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tune(tuneSEXP);
    Rcpp::traits::input_parameter< const int >::type ntemperatures(ntemperaturesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec >::type temperature_ladder(temperature_ladderSEXP);
    Rcpp::traits::input_parameter< const double >::type target_temp_swap_accept_ratio(target_temp_swap_accept_ratioSEXP);
    Rcpp::traits::input_parameter< const int >::type temp_window_size(temp_window_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type temp_window_size_growth_factor(temp_window_size_growth_factorSEXP);
    Rcpp::traits::input_parameter< const double >::type temp_ladder_learning_rate(temp_ladder_learning_rateSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type complete_swapping(complete_swappingSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hprobit_pt(xlist, ylist, mean_prior, prec_prior, fix_zero, ncategories, gamma_start, beta_start, tune, ntemperatures, temperature_ladder, target_temp_swap_accept_ratio, temp_window_size, temp_window_size_growth_factor, temp_ladder_learning_rate, iterations, burnin, thin, seed, complete_swapping, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fmeasure_distribution
arma::vec cpp_fmeasure_distribution(arma::mat predictions, arma::vec reference, int n_labels);
RcppExport SEXP _masteruppsatsr_cpp_fmeasure_distribution(SEXP predictionsSEXP, SEXP referenceSEXP, SEXP n_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type n_labels(n_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fmeasure_distribution(predictions, reference, n_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_classification_metric_distributions
Rcpp::List cpp_classification_metric_distributions(arma::mat predictions, arma::vec reference, int n_labels);
RcppExport SEXP _masteruppsatsr_cpp_classification_metric_distributions(SEXP predictionsSEXP, SEXP referenceSEXP, SEXP n_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type n_labels(n_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_classification_metric_distributions(predictions, reference, n_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_harmonic_rowmeans
arma::vec cpp_harmonic_rowmeans(arma::mat variables);
RcppExport SEXP _masteruppsatsr_cpp_harmonic_rowmeans(SEXP variablesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type variables(variablesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_harmonic_rowmeans(variables));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compare_distributions
Rcpp::List cpp_compare_distributions(arma::vec dist1, arma::vec dist2);
RcppExport SEXP _masteruppsatsr_cpp_compare_distributions(SEXP dist1SEXP, SEXP dist2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type dist1(dist1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dist2(dist2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compare_distributions(dist1, dist2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_diff_distributions
arma::vec cpp_diff_distributions(arma::vec dist1, arma::vec dist2);
RcppExport SEXP _masteruppsatsr_cpp_diff_distributions(SEXP dist1SEXP, SEXP dist2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type dist1(dist1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dist2(dist2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_diff_distributions(dist1, dist2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rmse_dist
arma::vec cpp_rmse_dist(arma::mat predictions, arma::mat reference, int ndraws);
RcppExport SEXP _masteruppsatsr_cpp_rmse_dist(SEXP predictionsSEXP, SEXP referenceSEXP, SEXP ndrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rmse_dist(predictions, reference, ndraws));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_masteruppsatsr_cpp_hprobit", (DL_FUNC) &_masteruppsatsr_cpp_hprobit, 14},
    {"_masteruppsatsr_cpp_hprobit_pt", (DL_FUNC) &_masteruppsatsr_cpp_hprobit_pt, 21},
    {"_masteruppsatsr_cpp_fmeasure_distribution", (DL_FUNC) &_masteruppsatsr_cpp_fmeasure_distribution, 3},
    {"_masteruppsatsr_cpp_classification_metric_distributions", (DL_FUNC) &_masteruppsatsr_cpp_classification_metric_distributions, 3},
    {"_masteruppsatsr_cpp_harmonic_rowmeans", (DL_FUNC) &_masteruppsatsr_cpp_harmonic_rowmeans, 1},
    {"_masteruppsatsr_cpp_compare_distributions", (DL_FUNC) &_masteruppsatsr_cpp_compare_distributions, 2},
    {"_masteruppsatsr_cpp_diff_distributions", (DL_FUNC) &_masteruppsatsr_cpp_diff_distributions, 2},
    {"_masteruppsatsr_cpp_rmse_dist", (DL_FUNC) &_masteruppsatsr_cpp_rmse_dist, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_masteruppsatsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
