# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_hprobit <- function(Xlist, Ylist, meanPrior, precPrior, fixZero, ncat, gammaStart, betaStart, tune, iterations, burnin, thin, seed, verbose) {
    .Call(`_masteruppsatsr_cpp_hprobit`, Xlist, Ylist, meanPrior, precPrior, fixZero, ncat, gammaStart, betaStart, tune, iterations, burnin, thin, seed, verbose)
}

cpp_fmeasure_distribution <- function(predictions, reference, n_labels) {
    .Call(`_masteruppsatsr_cpp_fmeasure_distribution`, predictions, reference, n_labels)
}

cpp_classification_metric_distributions <- function(predictions, reference, n_labels) {
    .Call(`_masteruppsatsr_cpp_classification_metric_distributions`, predictions, reference, n_labels)
}

cpp_harmonic_rowmeans <- function(variables) {
    .Call(`_masteruppsatsr_cpp_harmonic_rowmeans`, variables)
}

cpp_compare_distributions <- function(dist1, dist2) {
    .Call(`_masteruppsatsr_cpp_compare_distributions`, dist1, dist2)
}

cpp_diff_distributions <- function(dist1, dist2) {
    .Call(`_masteruppsatsr_cpp_diff_distributions`, dist1, dist2)
}

cpp_rmse_dist <- function(predictions, reference, ndraws) {
    .Call(`_masteruppsatsr_cpp_rmse_dist`, predictions, reference, ndraws)
}

